name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
      
    - name: Upload output file x86
      uses: actions/upload-artifact@v2
      with:
          name: curl-dump_${{ steps.vars.outputs.sha_short }}
          path: curl-dump_${{ steps.vars.outputs.sha_short }}
