name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Declare short commit variable
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Install MinGW-w64
        run: >
          sudo rm /var/lib/man-db/auto-update &&
          sudo DEBIAN_FRONTEND=noninteractive XZ_DEFAULTS="-T0" XZ_OPT="-T0" eatmydata
          apt install -y --no-install-recommends gcc-mingw-w64
      
      - name: Upload output file x86
        uses: actions/upload-artifact@v2
        with:
          name: curl-dump_${{ steps.vars.outputs.sha_short }}
          path: curl-dump_${{ steps.vars.outputs.sha_short }}
